### ISSUE TITLE
Timelines not updating/reloading on their own

### ISSUE THREAD

**Issue by Lertsenem** [RasmusLindroth/tut#182]
Hello,

I recently updated my Mastodon instance to the latest **v4.0.2** (using the [glitch-soc fork](https://glitch-soc.github.io/docs/)), and my tut to **v1.0.19** (amd64-static), and it looks like my home TL and my notifications are not updating on their own anymore.

I found the `:newest` command, which helps, but I did prefer the old automatic update method. Is this a conscious design decision ? Or is it a bug ?

**Comment by RasmusLindroth** [comment]
The problem seems to be with the fork or your installation, because it works for me with the latest version of tut running against Fosstodon on version 4.0.2.

But automatic updates relies  on streaming, so check to see if it's up and running on your server. I just host a server in a container for testing, so unfortunately I don't know how to troubleshoot your problem.

**Comment by Lertsenem** [comment]
> But automatic updates relies  on streaming, so check to see if it's up and running on your server. I just host a server in a container for testing, so unfortunately I don't know how to troubleshoot your problem.

It seems you're right, there are indeed error logs in my
mastodon-streaming process. I'll check those, thanks for pointing me in
the right direction!

**Comment by RasmusLindroth** [comment]
Yay, glad you fixed it :)
