### ISSUE TITLE
Switch from INI to TOML

### ISSUE THREAD

**Issue by justjosias** [RasmusLindroth/tut#20]
The [TOML configuration language](https://github.com/toml-lang/toml) is very similar to INI, but has a complete standard.

**Comment by RasmusLindroth** [comment]
I tried TOML first I think and If I recall correctly I settled with ini because of the available parsing packages. This package preserved comments better than other packages.

Now I don't see why I should change as it would break compatability with previous versions and this seems to work just fine.

I will leave this open if you have some more reason why it would be better to switch. Thanks for the input.

**Comment by justjosias** [comment]
I believe the file itself is both valid INI and TOML. The main difference would be spacing and the file extension. Also, both could be supported for a release cycle if you really wanted.

Also, I have used go-toml several times, and it works very well. 

I understand if you don't want to though. I was bringing up a suggestion from my experience with both formats.

> This package preserved comments better than other packages.

Can you elaborate here?
