### ISSUE TITLE
Please add so it auto-updates for real.

### ISSUE THREAD

**Issue by r3k2** [RasmusLindroth/tut#211]
Hello, I have been using TUT since when you had it alpha couple years now or more, and the auto-update feature is just not working for me, it grabs new toots, but they get scrolled down  and stack on top, I have my PC's on 24/7 like most people, when I leave and come back 12 hours later I have to scroll up ALL the toots like 10 m for each account/windows this is such a pain in the ass, can we add an option to **really** auto-update? whats happening now is that  the older toots do not go down in time so it does not update, instead new toots they stack on top for hours until I come back and scroll up, then having to pick up. I rather go back if I'd like to, then to have to go up for 10-20 m for each of my 4 accounts… You know how much waste of time is that?

**Comment by RasmusLindroth** [comment]
Can't you just press `Home` or lowercase `g` to get all the way to the top?

**Comment by RasmusLindroth** [comment]
A stick to the top options should be quite easy to implement, I'll look into it :)
Hopefully I'll have some time at Christmas to work some more on tut

**Comment by HelmicNewciv** [comment]
The current behavior does have the benefit of putting less strain on the instance, which - since tut doesn't actually _display_ the posts that are scrolling but just their username - seems a bit useless, at least on the federated timeline where you're not going to be recognizing people by just their screen name.

Now, if there were an option to do message previews, or perhaps going for *just* displaying the timelines in columns or rows however the user configured and displaying message previews like that, and then switching to a fullscreen view or switching back to the current layout of tut with a big 'ole message screen and tiny compact feeds, , then I can see that being really useful, because then you're getting a stream of actual readable messages and can spot interesting stuff as it scrolls by.

**Comment by Glog78** [comment]
![image](https://user-images.githubusercontent.com/7598856/206858351-b13a5a9f-969d-4686-b1b9-194f5572a28d.png)

There is a preview way ... you just have to setup your tut in a nice way

for example i have always above the timelines and below the  preview of most of the toots. (see screenshot)
i switch between timelines with leader 1 to x

**Comment by RasmusLindroth** [comment]
Now you can set `stick-to-top=true` under general :)

**Comment by r3k2** [comment]
nice! works like a charm thank you <3
