### ISSUE TITLE
Allowing of spaces in header titles would be sweet

### ISSUE THREAD

**Issue by toxision** [RasmusLindroth/tut#217]
Hi
it's me....again ;)
Just saying from the title, a possibility to add spaces into table headers would be a nice benefit.
![Screenshot_2022-12-14_00-14-38](https://user-images.githubusercontent.com/71572691/207465596-7bd63019-d32b-4211-83ca-e5907086379f.png)

Cheers,
Chris

**Comment by RasmusLindroth** [comment]
It's because the package that is used treats the hashtag as comment, so right now I'll have to leave this issue open. But you can use a tab character instead. If the tab is to large you could try some of these spaces, copy the space in the sample cell and paste it into your configuration file.

https://jkorpela.fi/chars/spaces.html
